spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 記得這行要讓 Render 執行正確的初始化腳本
spring.sql.init.data-locations=classpath:data-prod.sql